version: '3.5'

services:
  gaming-shop-api:
    container_name: gaming-shop-api
    build:
      context: .
    ports:
      - '1337:1337'
    networks:
      - gaming-shop-network

networks:
  gaming-shop-network:
    external: true
